CC = g++
CFLAGS = -g -Wall
TARGET = isp_determiner_test

default: $(TARGET)

$(TARGET): $(TARGET).cxx
	$(CC) $(CFLAGS) -o $(TARGET) $(TARGET).cxx

request_distribution_listener_test: request_distribution_listener_test.cxx
	$(CC) $(CFLAGS) -o request_distribution_listener_test request_distribution_listener_test.cxx
