.TH "md_src_sub-routines_README" 3 "Tue Mar 10 2020" "Version 0.5" "Afkanerd-DekuDaemon" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md_src_sub-routines_README \- Important notes 

.IP "\(bu" 2
SSH would have to have passed fingerprint after a \&.pub added, because system cannot manually enter password 
.PP

