.TH "Modem" 3 "Tue Mar 10 2020" "Version 0.5" "Afkanerd-DekuDaemon" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Modem
.SH SYNOPSIS
.br
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum \fBSTATE\fP { \fBTEST\fP, \fBPRODUCTION\fP }"
.br
.ti -1c
.RI "enum \fBTYPE\fP { \fBSSH\fP, \fBMMCLI\fP }"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBModem\fP (map< string, string > configs, STATE state=TEST)"
.br
.ti -1c
.RI "\fBModem\fP (const \fBModem\fP &modem)"
.br
.ti -1c
.RI "void \fBsetIndex\fP (string index)"
.br
.ti -1c
.RI "void \fBsetIMEI\fP (string IMEI)"
.br
.ti -1c
.RI "void \fBsetISP\fP (string ISP)"
.br
.ti -1c
.RI "void \fBsetKeepAlive\fP (bool keepAlive)"
.br
.ti -1c
.RI "void \fBstart\fP ()"
.br
.ti -1c
.RI "void \fBsetThreadSafety\fP (bool thread_safety)"
.br
.ti -1c
.RI "void \fBsetType\fP (string type)"
.br
.ti -1c
.RI "string \fBgetIndex\fP () const"
.br
.ti -1c
.RI "string \fBgetISP\fP () const"
.br
.ti -1c
.RI "string \fBgetIMEI\fP () const"
.br
.ti -1c
.RI "string \fBgetErrorLogs\fP ()"
.br
.ti -1c
.RI "string \fBgetInfo\fP () const"
.br
.ti -1c
.RI "TYPE \fBgetType\fP () const"
.br
.ti -1c
.RI "\fBoperator bool\fP () const"
.br
.ti -1c
.RI "bool \fBoperator==\fP (\fBModem\fP modem) const"
.br
.ti -1c
.RI "bool \fBoperator==\fP (\fBModem\fP *modem) const"
.br
.ti -1c
.RI "bool \fBoperator>\fP (\fBModem\fP modem) const"
.br
.ti -1c
.RI "bool \fBoperator<\fP (\fBModem\fP modem) const"
.br
.ti -1c
.RI "bool \fBend\fP ()"
.br
.ti -1c
.RI "bool \fBsend_sms\fP (string message, string number)"
.br
.ti -1c
.RI "bool \fBmmcli_send_sms\fP (string message, string number)"
.br
.ti -1c
.RI "bool \fBssh_send_sms\fP (string message, string number)"
.br
.ti -1c
.RI "bool \fBgetKeepAlive\fP () const"
.br
.ti -1c
.RI "bool \fBgetThreadSafety\fP () const"
.br
.ti -1c
.RI "map< string, string > \fBrequest_job\fP (string path_dir_request)"
.br
.ti -1c
.RI "map< string, string > \fBgetConfigs\fP () const"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "STATE \fBstate\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Afkanerd-DekuDaemon from the source code\&.
