.TH "Modems" 3 "Tue Mar 10 2020" "Version 0.5" "Afkanerd-DekuDaemon" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Modems
.SH SYNOPSIS
.br
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum \fBSTATE\fP { \fBTEST\fP, \fBPRODUCTION\fP }"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBModems\fP (STATE state)"
.br
.ti -1c
.RI "void \fB__INIT__\fP (map< string, string > configs)"
.br
.ti -1c
.RI "void \fBstartAllModems\fP ()"
.br
.ti -1c
.RI "vector< string > \fBgetAllIndexes\fP ()"
.br
.ti -1c
.RI "vector< string > \fBgetAllISP\fP ()"
.br
.ti -1c
.RI "vector< string > \fBgetAllIMEI\fP ()"
.br
.ti -1c
.RI "vector< \fBModem\fP * > \fBgetAllModems\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "STATE \fBstate\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Afkanerd-DekuDaemon from the source code\&.
