.TH "USSD" 3 "Tue Mar 10 2020" "Version 0.5" "Afkanerd-DekuDaemon" \" -*- nroff -*-
.ad l
.nh
.SH NAME
USSD
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBUSSD\fP (map< string, string >)"
.br
.ti -1c
.RI "\fBUSSD\fP (string, map< string, string >)"
.br
.ti -1c
.RI "string \fBinitiate\fP (string)"
.br
.ti -1c
.RI "string \fBrespond\fP (string)"
.br
.ti -1c
.RI "string \fBstatus\fP ()"
.br
.ti -1c
.RI "multimap< string, string > \fBinitiate_series\fP (vector< string >)"
.br
.ti -1c
.RI "multimap< string, string > \fBinitiate_series\fP (vector< string >, vector< string >)"
.br
.ti -1c
.RI "bool \fBcancel\fP ()"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Afkanerd-DekuDaemon from the source code\&.
